package ContadorApp;


/**
* ContadorApp/ContadorPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contador.idl
* sábado 14 de abril de 2012 07H40' CDT
*/

public abstract class ContadorPOA extends org.omg.PortableServer.Servant
 implements ContadorApp.ContadorOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_valor", new java.lang.Integer (0));
    _methods.put ("_set_valor", new java.lang.Integer (1));
    _methods.put ("inc", new java.lang.Integer (2));
    _methods.put ("dec", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ContadorApp/Contador/_get_valor
       {
         int $result = (int)0;
         $result = this.valor ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // ContadorApp/Contador/_set_valor
       {
         int newValor = in.read_long ();
         this.valor (newValor);
         out = $rh.createReply();
         break;
       }

       case 2:  // ContadorApp/Contador/inc
       {
         int $result = (int)0;
         $result = this.inc ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // ContadorApp/Contador/dec
       {
         int $result = (int)0;
         $result = this.dec ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ContadorApp/Contador:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Contador _this() 
  {
    return ContadorHelper.narrow(
    super._this_object());
  }

  public Contador _this(org.omg.CORBA.ORB orb) 
  {
    return ContadorHelper.narrow(
    super._this_object(orb));
  }


} // class ContadorPOA
