package ContadorApp;


/**
* ContadorApp/ContadorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contador.idl
* sábado 14 de abril de 2012 07H40' CDT
*/

public interface ContadorOperations 
{
  int valor ();
  void valor (int newValor);
  int inc ();
  int dec ();
} // interface ContadorOperations
