package ContadorApp;


/**
* ContadorApp/Contador.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contador.idl
* sábado 14 de abril de 2012 07H40' CDT
*/

public interface Contador extends ContadorOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Contador
