package ContadorApp;


/**
* ContadorApp/ContadorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contador.idl
* miércoles 18 de abril de 2012 09H13' CDT
*/

public interface ContadorOperations 
{
  int valor ();
  void valor (int newValor);
  int inc ();
  int dec ();
  void shutdown ();
} // interface ContadorOperations
