package ContadorApp;

/**
* ContadorApp/ContadorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Contador.idl
* sábado 14 de abril de 2012 07H40' CDT
*/

public final class ContadorHolder implements org.omg.CORBA.portable.Streamable
{
  public ContadorApp.Contador value = null;

  public ContadorHolder ()
  {
  }

  public ContadorHolder (ContadorApp.Contador initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ContadorApp.ContadorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ContadorApp.ContadorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ContadorApp.ContadorHelper.type ();
  }

}
